import { Product } from "@/types/product";
import { NewsItem } from "@/types/news";

export const DUMMY_PRODUCTS: Product[] = [
  {
    id: "1",
    company_name: "삼성생명",
    product_name: "삼성생명 종신보험 플러스",
    insurance_type: "life",
    insurance_subtype: "종신보험",
    monthly_premium: 85000,
    coverage_amount: 100000000,
    coverage_period: "종신",
    payment_period: "20년납",
    guarantee_rate: 2.5,
    key_features: { highlights: ["사망보장 1억원", "재해사망 추가보장", "납입면제 특약"] },
  },
  {
    id: "2",
    company_name: "한화생명",
    product_name: "한화생명 종신보험 스마트",
    insurance_type: "life",
    insurance_subtype: "종신보험",
    monthly_premium: 78000,
    coverage_amount: 100000000,
    coverage_period: "종신",
    payment_period: "20년납",
    guarantee_rate: 2.25,
    key_features: { highlights: ["사망보장 1억원", "건강할인 특약", "해약환급금 선택형"] },
  },
  {
    id: "3",
    company_name: "교보생명",
    product_name: "교보생명 무배당 종신보험",
    insurance_type: "life",
    insurance_subtype: "종신보험",
    monthly_premium: 92000,
    coverage_amount: 100000000,
    coverage_period: "종신",
    payment_period: "20년납",
    guarantee_rate: 2.75,
    key_features: { highlights: ["사망보장 1억원", "3대질병 납입면제", "연금전환 가능"] },
  },
  {
    id: "4",
    company_name: "삼성화재",
    product_name: "삼성화재 운전자보험",
    insurance_type: "non_life",
    insurance_subtype: "운전자보험",
    monthly_premium: 25000,
    coverage_amount: 30000000,
    coverage_period: "80세만기",
    payment_period: "전기납",
    guarantee_rate: null,
    key_features: { highlights: ["교통사고 처리지원금 3천만원", "벌금 2천만원", "변호사 선임비"] },
  },
  {
    id: "5",
    company_name: "DB손해보험",
    product_name: "DB손해보험 운전자보험 프리미엄",
    insurance_type: "non_life",
    insurance_subtype: "운전자보험",
    monthly_premium: 28000,
    coverage_amount: 50000000,
    coverage_period: "80세만기",
    payment_period: "전기납",
    guarantee_rate: null,
    key_features: { highlights: ["교통사고 처리지원금 5천만원", "벌금 3천만원", "자동차사고 부상치료비"] },
  },
  {
    id: "6",
    company_name: "현대해상",
    product_name: "현대해상 운전자보험 굿앤굿",
    insurance_type: "non_life",
    insurance_subtype: "운전자보험",
    monthly_premium: 23000,
    coverage_amount: 30000000,
    coverage_period: "80세만기",
    payment_period: "전기납",
    guarantee_rate: null,
    key_features: { highlights: ["교통사고 처리지원금 3천만원", "면허취소/정지 위로금", "자전거사고 보장"] },
  },
  {
    id: "7",
    company_name: "삼성화재",
    product_name: "삼성화재 실손의료보험 (4세대)",
    insurance_type: "health",
    insurance_subtype: "실손의료보험",
    monthly_premium: 15000,
    coverage_amount: 50000000,
    coverage_period: "15년 (자동갱신)",
    payment_period: "전기납",
    guarantee_rate: null,
    key_features: { highlights: ["급여 본인부담금 80%", "비급여 70%", "통원 1일 20만원"] },
  },
  {
    id: "8",
    company_name: "KB손해보험",
    product_name: "KB손해보험 실손의료보험 (4세대)",
    insurance_type: "health",
    insurance_subtype: "실손의료보험",
    monthly_premium: 14500,
    coverage_amount: 50000000,
    coverage_period: "15년 (자동갱신)",
    payment_period: "전기납",
    guarantee_rate: null,
    key_features: { highlights: ["급여 본인부담금 80%", "비급여 70%", "통원 1일 20만원"] },
  },
  {
    id: "9",
    company_name: "한화생명",
    product_name: "한화생명 암보험 무배당",
    insurance_type: "third_party",
    insurance_subtype: "암보험",
    monthly_premium: 35000,
    coverage_amount: 50000000,
    coverage_period: "100세만기",
    payment_period: "20년납",
    guarantee_rate: null,
    key_features: { highlights: ["일반암 5천만원", "소액암 1천만원", "암 수술비 500만원"] },
  },
  {
    id: "10",
    company_name: "교보생명",
    product_name: "교보생명 건강보험 올인원",
    insurance_type: "third_party",
    insurance_subtype: "건강보험",
    monthly_premium: 45000,
    coverage_amount: 50000000,
    coverage_period: "100세만기",
    payment_period: "20년납",
    guarantee_rate: null,
    key_features: { highlights: ["3대질병 진단금 5천만원", "뇌출혈 3천만원", "급성심근경색 3천만원"] },
  },
  {
    id: "11",
    company_name: "DB손해보험",
    product_name: "DB손해보험 암보험 다이렉트",
    insurance_type: "third_party",
    insurance_subtype: "암보험",
    monthly_premium: 28000,
    coverage_amount: 30000000,
    coverage_period: "80세만기",
    payment_period: "20년납",
    guarantee_rate: null,
    key_features: { highlights: ["일반암 3천만원", "유사암 1천만원", "암 입원일당 5만원"] },
  },
  {
    id: "12",
    company_name: "메리츠화재",
    product_name: "메리츠화재 실손의료보험 (4세대)",
    insurance_type: "health",
    insurance_subtype: "실손의료보험",
    monthly_premium: 14200,
    coverage_amount: 50000000,
    coverage_period: "15년 (자동갱신)",
    payment_period: "전기납",
    guarantee_rate: null,
    key_features: { highlights: ["급여 본인부담금 80%", "비급여 70%", "통원 1일 20만원"] },
  },
  {
    id: "13",
    company_name: "현대해상",
    product_name: "현대해상 실손의료보험 (4세대)",
    insurance_type: "health",
    insurance_subtype: "실손의료보험",
    monthly_premium: 14800,
    coverage_amount: 50000000,
    coverage_period: "15년 (자동갱신)",
    payment_period: "전기납",
    guarantee_rate: null,
    key_features: { highlights: ["급여 본인부담금 80%", "비급여 70%", "통원 1일 20만원"] },
  },
  {
    id: "14",
    company_name: "삼성생명",
    product_name: "삼성생명 연금보험 스마트",
    insurance_type: "life",
    insurance_subtype: "연금보험",
    monthly_premium: 300000,
    coverage_amount: 200000000,
    coverage_period: "종신",
    payment_period: "10년납",
    guarantee_rate: 2.0,
    key_features: { highlights: ["확정금리 2.0%", "종신연금 선택 가능", "비과세 혜택"] },
  },
  {
    id: "15",
    company_name: "한화생명",
    product_name: "한화생명 연금보험 플러스",
    insurance_type: "life",
    insurance_subtype: "연금보험",
    monthly_premium: 250000,
    coverage_amount: 150000000,
    coverage_period: "종신",
    payment_period: "10년납",
    guarantee_rate: 1.85,
    key_features: { highlights: ["확정금리 1.85%", "연금개시 후 사망보장", "중도인출 가능"] },
  },
  {
    id: "16",
    company_name: "메리츠화재",
    product_name: "메리츠화재 운전자보험 무배당",
    insurance_type: "non_life",
    insurance_subtype: "운전자보험",
    monthly_premium: 22000,
    coverage_amount: 30000000,
    coverage_period: "80세만기",
    payment_period: "전기납",
    guarantee_rate: null,
    key_features: { highlights: ["교통사고 처리지원금 3천만원", "벌금 2천만원", "자동차사고 성형수술비"] },
  },
  {
    id: "17",
    company_name: "삼성화재",
    product_name: "삼성화재 암보험 무배당",
    insurance_type: "third_party",
    insurance_subtype: "암보험",
    monthly_premium: 38000,
    coverage_amount: 50000000,
    coverage_period: "100세만기",
    payment_period: "20년납",
    guarantee_rate: null,
    key_features: { highlights: ["일반암 5천만원", "소액암 2천만원", "암 수술비 1천만원", "항암치료비"] },
  },
  {
    id: "18",
    company_name: "KB손해보험",
    product_name: "KB손해보험 간병보험",
    insurance_type: "third_party",
    insurance_subtype: "간병보험",
    monthly_premium: 42000,
    coverage_amount: 30000000,
    coverage_period: "100세만기",
    payment_period: "20년납",
    guarantee_rate: null,
    key_features: { highlights: ["치매 진단금 3천만원", "장기요양 월 100만원", "간병인 사용비 보장"] },
  },
  {
    id: "19",
    company_name: "교보생명",
    product_name: "교보생명 어린이보험 꿈나무",
    insurance_type: "third_party",
    insurance_subtype: "어린이보험",
    monthly_premium: 55000,
    coverage_amount: 30000000,
    coverage_period: "100세만기",
    payment_period: "20년납",
    guarantee_rate: null,
    key_features: { highlights: ["소아암 3천만원", "골절 치료비", "입원일당 5만원", "수술비 보장"] },
  },
  {
    id: "20",
    company_name: "DB손해보험",
    product_name: "DB손해보험 화재보험 프리미엄",
    insurance_type: "non_life",
    insurance_subtype: "화재보험",
    monthly_premium: 18000,
    coverage_amount: 100000000,
    coverage_period: "1년 (자동갱신)",
    payment_period: "월납",
    guarantee_rate: null,
    key_features: { highlights: ["화재손해 1억원", "폭발/파열 보장", "임시거주비 지원", "배상책임"] },
  },
];

export const DUMMY_NEWS: NewsItem[] = [
  {
    id: "1",
    title: "4세대 실손보험 가입자 1000만명 돌파... 보험료 인하 효과",
    description: "4세대 실손의료보험 가입자가 출시 2년 만에 1000만명을 돌파했다. 비급여 보장 축소와 자기부담금 확대로 보험료가 기존 대비 30% 이상 낮아진 것이 주효했다는 분석이다.",
    publisher: "한국경제",
    published_at: "2026-03-25T09:00:00",
    category: "health",
    original_url: "https://www.hankyung.com/economy/insurance",
    thumbnail_url: null,
  },
  {
    id: "2",
    title: "금감원, 보험사 불완전판매 제재 강화 방침",
    description: "금융감독원이 보험 불완전판매에 대한 제재를 강화하겠다고 밝혔다. 특히 고령자 대상 과잉 판매와 승환계약에 대한 모니터링을 확대할 계획이다.",
    publisher: "매일경제",
    published_at: "2026-03-24T14:30:00",
    category: "policy",
    original_url: "https://www.mk.co.kr/news/economy",
    thumbnail_url: null,
  },
  {
    id: "3",
    title: "삼성생명, 신규 종신보험 출시... 해약환급금 선택형 도입",
    description: "삼성생명이 해약환급금을 선택할 수 있는 새로운 형태의 종신보험을 출시했다. 저해약환급금형 선택 시 보험료를 최대 25% 절감할 수 있다.",
    publisher: "서울경제",
    published_at: "2026-03-24T10:00:00",
    category: "life",
    original_url: "https://www.sedaily.com/NewsView/finance",
    thumbnail_url: null,
  },
  {
    id: "4",
    title: "자동차보험료 평균 3.2% 인상... 수리비 상승 영향",
    description: "주요 손해보험사들이 자동차보험료를 평균 3.2% 인상했다. 자동차 부품값과 수리비 상승이 주요 원인으로 꼽힌다.",
    publisher: "조선비즈",
    published_at: "2026-03-23T16:00:00",
    category: "non_life",
    original_url: "https://biz.chosun.com/topics/insurance",
    thumbnail_url: null,
  },
  {
    id: "5",
    title: "보험업계 1분기 실적 호조... 투자이익 개선 효과",
    description: "주요 보험사들의 1분기 실적이 예상을 상회했다. 금리 안정화에 따른 투자이익 개선과 보험 인수 이익 증가가 주된 요인으로 분석된다.",
    publisher: "이데일리",
    published_at: "2026-03-23T11:00:00",
    category: "market",
    original_url: "https://www.edaily.co.kr/news/finance",
    thumbnail_url: null,
  },
  {
    id: "6",
    title: "KB손해보험, AI 기반 보험금 심사 시스템 도입",
    description: "KB손해보험이 AI를 활용한 보험금 심사 자동화 시스템을 도입했다. 기존 평균 7일 소요되던 심사 기간이 2일로 단축될 전망이다.",
    publisher: "디지털타임스",
    published_at: "2026-03-22T15:00:00",
    category: "market",
    original_url: "https://www.dt.co.kr/contents.html?article_no=insurance",
    thumbnail_url: null,
  },
  {
    id: "7",
    title: "메리츠화재, 무해지환급금형 건강보험 리뉴얼 출시",
    description: "메리츠화재가 무해지환급금형 건강보험을 리뉴얼하여 출시했다. 3대 질병 진단금과 수술비를 강화하고 보험료는 기존 대비 15% 낮췄다.",
    publisher: "파이낸셜뉴스",
    published_at: "2026-03-22T09:30:00",
    category: "non_life",
    original_url: "https://www.fnnews.com/news/finance",
    thumbnail_url: null,
  },
  {
    id: "8",
    title: "보험연구원 '고령화 시대, 간병보험 수요 급증' 전망",
    description: "보험연구원이 발표한 보고서에 따르면, 초고령사회 진입을 앞두고 간병보험 수요가 향후 5년간 연평균 20% 이상 증가할 것으로 전망된다.",
    publisher: "뉴스핌",
    published_at: "2026-03-21T14:00:00",
    category: "market",
    original_url: "https://www.newspim.com/news/finance",
    thumbnail_url: null,
  },
  {
    id: "9",
    title: "금융위, 보험 소비자 보호 강화 위한 제도 개선안 발표",
    description: "금융위원회가 보험 소비자 보호를 위한 제도 개선안을 발표했다. 약관 핵심 사항 요약 의무화, 청약 철회 기간 확대 등이 포함됐다.",
    publisher: "연합뉴스",
    published_at: "2026-03-21T10:00:00",
    category: "policy",
    original_url: "https://www.yna.co.kr/economy/finance",
    thumbnail_url: null,
  },
  {
    id: "10",
    title: "현대해상, 반려동물 보험 가입 건수 전년比 50% 증가",
    description: "현대해상이 반려동물 보험 가입 건수가 전년 대비 50% 증가했다고 밝혔다. 반려동물 양육 가구 증가와 의료비 부담이 주요 원인으로 분석된다.",
    publisher: "머니투데이",
    published_at: "2026-03-20T16:30:00",
    category: "non_life",
    original_url: "https://news.mt.co.kr/finance",
    thumbnail_url: null,
  },
  {
    id: "11",
    title: "실손보험 자기부담률 차등화 시행 1년... 도덕적 해이 감소 효과",
    description: "실손보험 자기부담률 차등화 시행 1년을 맞아 보험금 청구 건수가 12% 감소한 것으로 나타났다. 과다 의료 이용이 줄어든 효과로 분석된다.",
    publisher: "한국일보",
    published_at: "2026-03-20T11:00:00",
    category: "health",
    original_url: "https://www.hankookilbo.com/News/economy",
    thumbnail_url: null,
  },
  {
    id: "12",
    title: "교보생명, 변액보험 수익률 업계 1위... 연 8.3% 기록",
    description: "교보생명의 변액보험 수익률이 업계 최고인 연 8.3%를 기록했다. 글로벌 주식시장 호조와 적극적인 펀드 운용 전략이 주효했다는 평가다.",
    publisher: "아시아경제",
    published_at: "2026-03-19T15:00:00",
    category: "life",
    original_url: "https://www.asiae.co.kr/finance",
    thumbnail_url: null,
  },
];
